### ISSUE TITLE
Returning to start position of an operation.

### ISSUE THREAD

**Issue by lar3ry** [fraz3alpha/k40-whisperer#1]
Not sure if this is the right place, but it seems the best I could find.

I see that when an operaiton finished, the head returns to the position it was when the opration started. Very handy, because you can then do a different opration (different colour). However, if an operation is stopped (by the Stop button), then accepted with the OK button, it does not return to the starting point. Several time I have had the need to stop the operaton, make changes in the file or change the current, then re-start. It would be REAL nice if the head could return (always or with an option), to the starting point after a manual stop. Thanks for listening.

**Comment by fraz3alpha** [comment]
This isn't the original project - I forked it on Github to look at making some changes. You should look at the original repo (link in GitHub) or the scortchworks site

**Comment by lar3ry** [comment]
Thanks for responding, Andy. Sorry to bother you.
I'm having a lot of difficulty finding the source.
I'll drop an email to scorch@scorchworks.com
Perhaps I'll just download your github fork and see if I can do something with it.

Larry

**Comment by fraz3alpha** [comment]
I've just remembered, it wasn't a git repo I forked, it was just a copy of the downloaded source bundle from https://www.scorchworks.com/K40whisperer/k40whisperer.html#download .

If you run K40 whisperer on a Mac or Linux, it's just python - so there isn't a difference between what you run and the source, you just run these python scripts.

**Comment by lar3ry** [comment]
Thanks a bunch Andy!
I must have looked at that page 30 times, and never noticed the source column.
<slapping forehead>

Again, sorry to have bothered you.

Larry

On 2 May 2019 at 9:13, Andy Taylor wrote:
> I've just remembered, it wasn't a git repo I forked, it was just a copy of the downloaded source 
> bundle from https://www.scorchworks.com/K40whisperer/k40whisperer.html#download .
> If you run K40 whisperer on a Mac or Linux, it's just python - so there isn't a difference between 
> what you run and the source, you just run these python scripts.
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Magic trumps science for most people,
and wishful thinking drives a lot of decision-making.
    - Joe Haldeman
